Feat/upload snowflake icon
illacloud/illa-builder pull request #951
Opened 2023-02-16 15:21 UTC by shandamengcheng

## 📝 Description

Add a brief description.

## 💣 Is this a breaking change (Yes/No):

- [ ] Yes
- [x] No

## 🚧 How to migrate?

Don't need.

## 📝 Additional Information

lol

2023-02-16 16:14 UTC, AruSeito requested changes

2023-02-16 16:14 UTC, AruSeito commented on apps/builder/src/page/App/components/InspectPanel/style.ts
> +    align-self: center;
这个有跟松哥沟通过吗？当时是右侧输入框如果多行的话，会让 label 在最上侧，而不是居中对齐。
另外 display:block 这个会使双行的label 下划线占满行

2023-02-16 16:14 UTC, AruSeito commented on apps/builder/src/page/App/components/PanelSetters/IconSetter/baseIconSetter.tsx
> +  const handleMouseEnter = useCallback(() => {
用 css 做，hover 上去子元素显示。

2023-02-16 16:40 UTC, shandamengcheng commented on apps/builder/src/page/App/components/InspectPanel/interface.ts
> +  expectedTypes?: VALIDATION_TYPES[]
删除了该参数，是否左侧计算树的展示需要进行number过滤以及是否需要进行parseInt / parseFloat处理

2023-02-17 04:04 UTC, AruSeito approved these changes

2023-02-17 04:04 UTC, merged